site_name: Glasgow Project

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo1.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # 浅色
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    # 深色
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

markdown_extensions:
  - pymdownx.mark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/OSCOLA.js

nav:
  - Home: index.md

  - Dissertation: 
    - Dissertation: Dissertation/Dissertation.md
    - Deadlines: Dissertation/Deadlines.md
    - Websites and Files: Dissertation/Websites and Files.md
    - OSCOLA: Dissertation/OSCOLA.md

  - Course:
    - AI Law: Course/AI Law/AI Law.md
    - Contemporary IP: Course/Contemporary IP/Contemporary IP.md
    - Contemporary IP: Course/Contemporary IP/Contemporary IP 1.md
    - Copyright Law: Course/Copyright Law/Copyright Law.md
    - Information Law: Course/Information Law/Information Law.md
    - Investment Law: Course/Investment Law/Investment Law.md
    - Trademark Law: Course/Trademark Law/Trademark Law.md

plugins:
  - search
  - glightbox