site_name: Glasgow Project

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo1.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # 浅色
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    # 深色
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

markdown_extensions:
  - pymdownx.mark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/OSCOLA.js

nav:
  - Home: index.md

  - Resources:
    - '*AI Law': Resources/AI Law/AI Law.md
    - '*Contemporary IP': Resources/Contemporary IP/Contemporary IP.md
    - Contemporary IP: Resources/Contemporary IP/Contemporary IP 1.md
    - Copyright Law: Resources/Copyright Law/Copyright Law.md
    - Information Law: Resources/Information Law/Information Law.md
    - Investment Law: Resources/Investment Law/Investment Law.md
    - Trademark Law: Resources/Trademark Law/Trademark Law.md
    - OSCOLA: Resources/OSCOLA.md
    - Websites and Files: Resources/Websites and Files.md
    - Deadlines: Resources/Deadlines.md
  
  - Dissertation: Dissertation/Dissertation.md

plugins:
  - search
  - glightbox